[meta]
name = "test" 
seed = 42
epochs = 20
save_dir = "saved/" 
gradient_accumulation_steps = 2
use_amp = false # Whether to use Automatic Mixed Precision for speeding up - https://pytorch.org/docs/stable/amp.html
device_ids = "4,5" # set the gpu devices on which you want to train your model
sr = 16000
max_clip_grad_norm = 1.0 # torch.nn.utils.clip_grad_norm_


[train_dataset]
path = "base.base_dataset.BaseDataset"
    [train_dataset.args]
    path = "/data1/speech/khanhld/ASR-Wa2vec-Finetune/dataset/vi_450h/train/train.txt"
    preload_data = false
    delimiter = "|"
    # for vietnamese only, change chars_to_ignore that meets your language
    chars_to_ignore = '[^\ a-z0-9A-Z_àáãạảăắằẳẵặâấầẩẫậèéẹẻẽêềếểễệđìíĩỉịòóõọỏôốồổỗộơớờởỡợùúũụủưứừửữựỳỵỷỹýÀÁÃẠẢĂẮẰẲẴẶÂẤẦẨẪẬÈÉẸẺẼÊỀẾỂỄỆĐÌÍĨỈỊÒÓÕỌỎÔỐỒỔỖỘƠỚỜỞỠỢÙÚŨỤỦƯỨỪỬỮỰỲỴỶỸÝ]'
    min_duration = 0.5
    max_duration = 20
    nb_workers = 16
    
    [train_dataset.dataloader]
        batch_size = 8
        num_workers = 16
        pin_memory = true 
        drop_last = true
    [train_dataset.sampler]
        shuffle = true 
        drop_last = true

    
[val_dataset]
path = "base.base_dataset.BaseDataset"
    [val_dataset.args]
    path = "/data1/speech/khanhld/ASR-Wa2vec-Finetune/dataset/vi_450h/test/test.txt"
    preload_data = false
    delimiter = "|"
    # for vietnamese only, change chars_to_ignore that meets your language
    chars_to_ignore = '[^\ a-z0-9A-Z_àáãạảăắằẳẵặâấầẩẫậèéẹẻẽêềếểễệđìíĩỉịòóõọỏôốồổỗộơớờởỡợùúũụủưứừửữựỳỵỷỹýÀÁÃẠẢĂẮẰẲẴẶÂẤẦẨẪẬÈÉẸẺẼÊỀẾỂỄỆĐÌÍĨỈỊÒÓÕỌỎÔỐỒỔỖỘƠỚỜỞỠỢÙÚŨỤỦƯỨỪỬỮỰỲỴỶỸÝ]'
    nb_workers = 16

    [val_dataset.dataloader]
        batch_size =  1
        num_workers = 4

    [val_dataset.sampler]
        shuffle = false 
        drop_last = false

 
[optimizer]
lr = 5e-6


[scheduler] 
max_lr = 5e-5
    

[trainer]
path = "trainer.trainer.Trainer"
    [trainer.args]
    validation_interval = 500
    save_max_metric_score = false 
